// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package grapql

type Gif struct {
	ID  string `json:"id"`
	Gif string `json:"gif"`
}

type Profile struct {
	Email      string   `json:"email"`
	Mobile     string   `json:"mobile"`
	Username   string   `json:"username"`
	Avatar     string   `json:"avatar"`
	Categories []string `json:"categories"`
}

type User struct {
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Avatar   string `json:"avatar"`
	Username string `json:"username"`
}
