// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChatMSG          string
	Favorites        string
	HubUser          string
	Hubs             string
	SchemaMigrations string
	UserFavorite     string
	Users            string
}{
	ChatMSG:          "chat_msg",
	Favorites:        "favorites",
	HubUser:          "hub_user",
	Hubs:             "hubs",
	SchemaMigrations: "schema_migrations",
	UserFavorite:     "user_favorite",
	Users:            "users",
}
