// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testChatMSGS(t *testing.T) {
	t.Parallel()

	query := ChatMSGS()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testChatMSGSDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChatMSGSQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ChatMSGS().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChatMSGSSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChatMSGSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChatMSGSExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ChatMSGExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ChatMSG exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ChatMSGExists to return true, but got false.")
	}
}

func testChatMSGSFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	chatMSGFound, err := FindChatMSG(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if chatMSGFound == nil {
		t.Error("want a record, got nil")
	}
}

func testChatMSGSBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ChatMSGS().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testChatMSGSOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ChatMSGS().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testChatMSGSAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	chatMSGOne := &ChatMSG{}
	chatMSGTwo := &ChatMSG{}
	if err = randomize.Struct(seed, chatMSGOne, chatMSGDBTypes, false, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}
	if err = randomize.Struct(seed, chatMSGTwo, chatMSGDBTypes, false, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = chatMSGOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = chatMSGTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ChatMSGS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testChatMSGSCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	chatMSGOne := &ChatMSG{}
	chatMSGTwo := &ChatMSG{}
	if err = randomize.Struct(seed, chatMSGOne, chatMSGDBTypes, false, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}
	if err = randomize.Struct(seed, chatMSGTwo, chatMSGDBTypes, false, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = chatMSGOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = chatMSGTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func chatMSGBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func chatMSGAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatMSG) error {
	*o = ChatMSG{}
	return nil
}

func testChatMSGSHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ChatMSG{}
	o := &ChatMSG{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, chatMSGDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ChatMSG object: %s", err)
	}

	AddChatMSGHook(boil.BeforeInsertHook, chatMSGBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	chatMSGBeforeInsertHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.AfterInsertHook, chatMSGAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	chatMSGAfterInsertHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.AfterSelectHook, chatMSGAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	chatMSGAfterSelectHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.BeforeUpdateHook, chatMSGBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	chatMSGBeforeUpdateHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.AfterUpdateHook, chatMSGAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	chatMSGAfterUpdateHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.BeforeDeleteHook, chatMSGBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	chatMSGBeforeDeleteHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.AfterDeleteHook, chatMSGAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	chatMSGAfterDeleteHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.BeforeUpsertHook, chatMSGBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	chatMSGBeforeUpsertHooks = []ChatMSGHook{}

	AddChatMSGHook(boil.AfterUpsertHook, chatMSGAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	chatMSGAfterUpsertHooks = []ChatMSGHook{}
}

func testChatMSGSInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChatMSGSInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(chatMSGColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChatMSGToOneHubUsingHub(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ChatMSG
	var foreign Hub

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, chatMSGDBTypes, false, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, hubDBTypes, false, hubColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hub struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.HubID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Hub().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ChatMSGSlice{&local}
	if err = local.L.LoadHub(ctx, tx, false, (*[]*ChatMSG)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Hub == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Hub = nil
	if err = local.L.LoadHub(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Hub == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testChatMSGToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ChatMSG
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, chatMSGDBTypes, false, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ChatMSGSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*ChatMSG)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testChatMSGToOneSetOpHubUsingHub(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ChatMSG
	var b, c Hub

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, chatMSGDBTypes, false, strmangle.SetComplement(chatMSGPrimaryKeyColumns, chatMSGColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, hubDBTypes, false, strmangle.SetComplement(hubPrimaryKeyColumns, hubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, hubDBTypes, false, strmangle.SetComplement(hubPrimaryKeyColumns, hubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Hub{&b, &c} {
		err = a.SetHub(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Hub != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ChatMSGS[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.HubID != x.ID {
			t.Error("foreign key was wrong value", a.HubID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.HubID))
		reflect.Indirect(reflect.ValueOf(&a.HubID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.HubID != x.ID {
			t.Error("foreign key was wrong value", a.HubID, x.ID)
		}
	}
}
func testChatMSGToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ChatMSG
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, chatMSGDBTypes, false, strmangle.SetComplement(chatMSGPrimaryKeyColumns, chatMSGColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ChatMSGS[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testChatMSGSReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testChatMSGSReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChatMSGSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testChatMSGSSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ChatMSGS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	chatMSGDBTypes = map[string]string{`ID`: `text`, `HubID`: `text`, `GifData`: `bytea`, `CreateAt`: `timestamp without time zone`, `UserID`: `text`}
	_              = bytes.MinRead
)

func testChatMSGSUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(chatMSGPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(chatMSGAllColumns) == len(chatMSGPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testChatMSGSSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(chatMSGAllColumns) == len(chatMSGPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ChatMSG{}
	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, chatMSGDBTypes, true, chatMSGPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(chatMSGAllColumns, chatMSGPrimaryKeyColumns) {
		fields = chatMSGAllColumns
	} else {
		fields = strmangle.SetComplement(
			chatMSGAllColumns,
			chatMSGPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ChatMSGSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testChatMSGSUpsert(t *testing.T) {
	t.Parallel()

	if len(chatMSGAllColumns) == len(chatMSGPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ChatMSG{}
	if err = randomize.Struct(seed, &o, chatMSGDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ChatMSG: %s", err)
	}

	count, err := ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, chatMSGDBTypes, false, chatMSGPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChatMSG struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ChatMSG: %s", err)
	}

	count, err = ChatMSGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
