// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testHubUsers(t *testing.T) {
	t.Parallel()

	query := HubUsers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testHubUsersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHubUsersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := HubUsers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHubUsersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HubUserSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHubUsersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := HubUserExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if HubUser exists: %s", err)
	}
	if !e {
		t.Errorf("Expected HubUserExists to return true, but got false.")
	}
}

func testHubUsersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	hubUserFound, err := FindHubUser(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if hubUserFound == nil {
		t.Error("want a record, got nil")
	}
}

func testHubUsersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = HubUsers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testHubUsersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := HubUsers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testHubUsersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	hubUserOne := &HubUser{}
	hubUserTwo := &HubUser{}
	if err = randomize.Struct(seed, hubUserOne, hubUserDBTypes, false, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}
	if err = randomize.Struct(seed, hubUserTwo, hubUserDBTypes, false, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = hubUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = hubUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := HubUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testHubUsersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	hubUserOne := &HubUser{}
	hubUserTwo := &HubUser{}
	if err = randomize.Struct(seed, hubUserOne, hubUserDBTypes, false, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}
	if err = randomize.Struct(seed, hubUserTwo, hubUserDBTypes, false, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = hubUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = hubUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func hubUserBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func hubUserAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *HubUser) error {
	*o = HubUser{}
	return nil
}

func testHubUsersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &HubUser{}
	o := &HubUser{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, hubUserDBTypes, false); err != nil {
		t.Errorf("Unable to randomize HubUser object: %s", err)
	}

	AddHubUserHook(boil.BeforeInsertHook, hubUserBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	hubUserBeforeInsertHooks = []HubUserHook{}

	AddHubUserHook(boil.AfterInsertHook, hubUserAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	hubUserAfterInsertHooks = []HubUserHook{}

	AddHubUserHook(boil.AfterSelectHook, hubUserAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	hubUserAfterSelectHooks = []HubUserHook{}

	AddHubUserHook(boil.BeforeUpdateHook, hubUserBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	hubUserBeforeUpdateHooks = []HubUserHook{}

	AddHubUserHook(boil.AfterUpdateHook, hubUserAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	hubUserAfterUpdateHooks = []HubUserHook{}

	AddHubUserHook(boil.BeforeDeleteHook, hubUserBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	hubUserBeforeDeleteHooks = []HubUserHook{}

	AddHubUserHook(boil.AfterDeleteHook, hubUserAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	hubUserAfterDeleteHooks = []HubUserHook{}

	AddHubUserHook(boil.BeforeUpsertHook, hubUserBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	hubUserBeforeUpsertHooks = []HubUserHook{}

	AddHubUserHook(boil.AfterUpsertHook, hubUserAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	hubUserAfterUpsertHooks = []HubUserHook{}
}

func testHubUsersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHubUsersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(hubUserColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHubUserToOneHubUsingHub(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local HubUser
	var foreign Hub

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, hubUserDBTypes, false, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, hubDBTypes, false, hubColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hub struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.HubID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Hub().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := HubUserSlice{&local}
	if err = local.L.LoadHub(ctx, tx, false, (*[]*HubUser)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Hub == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Hub = nil
	if err = local.L.LoadHub(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Hub == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testHubUserToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local HubUser
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, hubUserDBTypes, false, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := HubUserSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*HubUser)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testHubUserToOneSetOpHubUsingHub(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a HubUser
	var b, c Hub

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, hubUserDBTypes, false, strmangle.SetComplement(hubUserPrimaryKeyColumns, hubUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, hubDBTypes, false, strmangle.SetComplement(hubPrimaryKeyColumns, hubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, hubDBTypes, false, strmangle.SetComplement(hubPrimaryKeyColumns, hubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Hub{&b, &c} {
		err = a.SetHub(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Hub != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.HubUsers[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.HubID != x.ID {
			t.Error("foreign key was wrong value", a.HubID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.HubID))
		reflect.Indirect(reflect.ValueOf(&a.HubID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.HubID != x.ID {
			t.Error("foreign key was wrong value", a.HubID, x.ID)
		}
	}
}
func testHubUserToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a HubUser
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, hubUserDBTypes, false, strmangle.SetComplement(hubUserPrimaryKeyColumns, hubUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.HubUsers[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testHubUsersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHubUsersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HubUserSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHubUsersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := HubUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	hubUserDBTypes = map[string]string{`ID`: `text`, `HubID`: `text`, `UserID`: `text`}
	_              = bytes.MinRead
)

func testHubUsersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(hubUserPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(hubUserAllColumns) == len(hubUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testHubUsersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(hubUserAllColumns) == len(hubUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &HubUser{}
	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, hubUserDBTypes, true, hubUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(hubUserAllColumns, hubUserPrimaryKeyColumns) {
		fields = hubUserAllColumns
	} else {
		fields = strmangle.SetComplement(
			hubUserAllColumns,
			hubUserPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := HubUserSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testHubUsersUpsert(t *testing.T) {
	t.Parallel()

	if len(hubUserAllColumns) == len(hubUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := HubUser{}
	if err = randomize.Struct(seed, &o, hubUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert HubUser: %s", err)
	}

	count, err := HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, hubUserDBTypes, false, hubUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HubUser struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert HubUser: %s", err)
	}

	count, err = HubUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
