// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ChatMSGS", testChatMSGSUpsert)

	t.Run("Favorites", testFavoritesUpsert)

	t.Run("HubUsers", testHubUsersUpsert)

	t.Run("Hubs", testHubsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("UserFavorites", testUserFavoritesUpsert)

	t.Run("Users", testUsersUpsert)
}
