// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserCategories(t *testing.T) {
	t.Parallel()

	query := UserCategories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserCategoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserCategoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserCategories().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserCategoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserCategorySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserCategoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserCategoryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserCategory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserCategoryExists to return true, but got false.")
	}
}

func testUserCategoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userCategoryFound, err := FindUserCategory(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userCategoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserCategoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserCategories().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserCategoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserCategories().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserCategoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userCategoryOne := &UserCategory{}
	userCategoryTwo := &UserCategory{}
	if err = randomize.Struct(seed, userCategoryOne, userCategoryDBTypes, false, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, userCategoryTwo, userCategoryDBTypes, false, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserCategoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userCategoryOne := &UserCategory{}
	userCategoryTwo := &UserCategory{}
	if err = randomize.Struct(seed, userCategoryOne, userCategoryDBTypes, false, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, userCategoryTwo, userCategoryDBTypes, false, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userCategoryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func userCategoryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCategory) error {
	*o = UserCategory{}
	return nil
}

func testUserCategoriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserCategory{}
	o := &UserCategory{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userCategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserCategory object: %s", err)
	}

	AddUserCategoryHook(boil.BeforeInsertHook, userCategoryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userCategoryBeforeInsertHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.AfterInsertHook, userCategoryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userCategoryAfterInsertHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.AfterSelectHook, userCategoryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userCategoryAfterSelectHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.BeforeUpdateHook, userCategoryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userCategoryBeforeUpdateHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.AfterUpdateHook, userCategoryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userCategoryAfterUpdateHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.BeforeDeleteHook, userCategoryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userCategoryBeforeDeleteHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.AfterDeleteHook, userCategoryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userCategoryAfterDeleteHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.BeforeUpsertHook, userCategoryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userCategoryBeforeUpsertHooks = []UserCategoryHook{}

	AddUserCategoryHook(boil.AfterUpsertHook, userCategoryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userCategoryAfterUpsertHooks = []UserCategoryHook{}
}

func testUserCategoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserCategoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userCategoryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserCategoryToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserCategory
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userCategoryDBTypes, false, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserCategorySlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*UserCategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserCategoryToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserCategory
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userCategoryDBTypes, false, strmangle.SetComplement(userCategoryPrimaryKeyColumns, userCategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserCategories[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUserCategoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserCategoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserCategorySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserCategoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userCategoryDBTypes = map[string]string{`ID`: `text`, `UserID`: `text`, `Category`: `text`}
	_                   = bytes.MinRead
)

func testUserCategoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userCategoryAllColumns) == len(userCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserCategoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userCategoryAllColumns) == len(userCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserCategory{}
	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userCategoryDBTypes, true, userCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userCategoryAllColumns, userCategoryPrimaryKeyColumns) {
		fields = userCategoryAllColumns
	} else {
		fields = strmangle.SetComplement(
			userCategoryAllColumns,
			userCategoryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserCategorySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserCategoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(userCategoryAllColumns) == len(userCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserCategory{}
	if err = randomize.Struct(seed, &o, userCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserCategory: %s", err)
	}

	count, err := UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userCategoryDBTypes, false, userCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserCategory struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserCategory: %s", err)
	}

	count, err = UserCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
